version: "3.7"
services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
  mongodb:
    image: "mongo:4.2"
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: mongodatabase
      ME_CONFIG_BASICAUTH_PASSWORD: mongodatabase
    depends_on:
      - mongodb
  web:
    image: "php:7.2-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "80:80"