version: "3.7"
services:
  db-mysql:
    image: "mysql:8.0"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: always
    volumes:
      - ./db-mysql/data:/var/lib/mysql
  db-mongo:
    image: "mongo:4.2"
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  web:
    image: "php:7.2-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "80:80"
