version: "3.7"
services:
  api:
    image: "node:10-slim"
    build: "./api"
    working_dir: "/home/node/app"
    container_name: node-container
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:3000"
  web:
    image: "php:7.2-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - api
